### ISSUE TITLE
postinstall throwing an error in Windows

### ISSUE THREAD

**Issue by dghelm** [radicle-dev/twemoji-svg-assets#4]
Something about the postinstall `cp` command is throwing errors on Windows:

`cp: target '$INIT_CWD/public/twemoji/' is not a directory`

Suggestions:
- May work to first call `mkdir`
- Replace with https://www.npmjs.com/package/@datawrapper/twemoji-svg or https://github.com/jakejarvis/twemoji-emojis
- Use something like https://github.com/sindresorhus/cpy-cli or https://www.npmjs.com/package/ncp to call copy command.

I'd be happy to look into what it takes to fix cross-platform installation that works for Windows.

**Comment by dghelm** [comment]
I also overlooked that this solution was made seemingly targeting Windows -- not sure if it's happy cross-platform though: https://github.com/bltavares/twemoji-svg-assets/blob/patch-1/package.json

**Comment by rudolfs** [comment]
Thanks for reporting this. Upstream isn't officially supported on Windows yet. However @bltavares [is working on windows support](https://github.com/radicle-dev/radicle-upstream/pull/1623) as part of a community effort to get it working.

To give some context, this package is only meant to work within the https://github.com/radicle-dev/radicle-upstream repository where the `../../public/twemoji` path should exist in any case.

I think it would make sense to ask how @bltavares got it working on windows first before trying to implement something.

**Comment by bltavares** [comment]
`radicle-upstream` does not use  yet the fixed version with #3 applied. Have you have this error from `radicle-upstream` or are you using  another repo?

**Comment by dghelm** [comment]
I was originally trying to run `radicle-upstream` master before working with your `backport-windows` branch, which fully compiles and runs on my machine. (Granted, I haven't tried much beyond getting Electron running.)

**Comment by rudolfs** [comment]
> I was originally trying to run radicle-upstream master before working with your backport-windows branch, which fully compiles and runs on my machine. (Granted, I haven't tried much beyond getting Electron running.)

Can we close this issue then?

**Comment by dghelm** [comment]
Yup, sorry for the confusion!
